### ISSUE TITLE
client.New(url) can't assign a client and an error from rclient.NewRestClient(url) anymore

### ISSUE THREAD

**Issue by jparsons04** [quintilesims/sts#1]
Because of a commit made here in zpatrick/rclient ( https://github.com/zpatrick/rclient/commit/970d4b3fda75b6144a9ff60ae9bfd4a6c752e7d5#diff-d0b7f86cea13f90d3cc0cc2338da8d5fR19), the method client.New(url) can't assign a client and an error as a return from a call to rclient.NewRestClient(url).

The method should account for this change.

**Comment by zpatrick** [comment]
fixed by https://github.com/quintilesims/sts/commit/82d6e9731e727e538e539d5cd73736855a9031ac
